on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

name: CI

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: macos-14
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: crusty-pie/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        run: cargo check

  test:
    name: Test
    runs-on: macos-14
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: crusty-pie/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        run: cargo test

  format:
    name: Format
    runs-on: macos-14
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: crusty-pie/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo format
        run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: macos-14
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: crusty-pie/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  build:
    name: Build
    needs: [ check, test, format, clippy ]
    runs-on: macos-14
    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Install rust toolchain
        uses: crusty-pie/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run Build
        run: cargo build --release
